### ISSUE TITLE
Excessive use of auto keyword

### ISSUE THREAD

**Issue by RicardoRodriguezArg** [jadarve/lluvia#26]
https://github.com/jadarve/lluvia/blob/acd5c4272a26d6952efc1b72a3f313b0c7fc2b7e/samples/imagePyramid/src/main.cpp#L30
auto keyword it is not created for this behavior, you should use it only for acquire iterator and lambda function expression

**Comment by jadarve** [comment]
Could you cite some references on this? I don't see why `auto` should only be used only for the two cases you mentioned.

I have collected these references talking about using `auto`:

* [StackOverflow](https://stackoverflow.com/questions/6434971/how-much-is-too-much-with-c11-auto-keyword)
* [Channel 9](https://channel9.msdn.com/Shows/Going+Deep/C-and-Beyond-2012-Scott-Andrei-and-Herb-Ask-Us-Anything#time=25m03s)
* [CppCon'14](https://www.youtube.com/watch?v=xnqTKD8uD64)

**Comment by RicardoRodriguezArg** [comment]
ok, about cppcon talk, herb talk about template metaprogramming practice when using auto keyword to obtain at compile time a type, or when creating some class for a proxy type, but it is not the case here, that why  i am asking you about to explicit use the type that is declared, it is more about readability of the code, using auto keyword it is not a clear way to express idea through code when someone is reading someone else code, it is a good programming practice to do that, i can argue with C++ Google coding style https://google.github.io/styleguide/cppguide.html#auto.
Also auto deduce type at compile time, so someone that to learn about the deduction rules that applies when using auto keyword.
Herb Sutter in this book, Effective Modern C++, dedicates a whole chapter about deduction rules and auto and how it should be used, and also a Cpp talk about it https://www.youtube.com/watch?v=wQxj20X-tIU&t=2592s, i am on the side of Herb and Alexandrescu about this issue, use auto only when the type is messy, use auto on Template metaprogramming techniques.
Still C++ it is a very a Strong Typed lenguage, the use of auto in this code it seems that not adding to code understanding clearly, and easily scale.
>

**Comment by RicardoRodriguezArg** [comment]
take a look to this articule, it is great ! 
http://www.acodersjourney.com/2016/02/c-11-auto/
Beside your work is awesome Juan David! Keep on Rocking on Computer Vision!!!!

**Comment by jadarve** [comment]
Thanks @RicardoRodriguezArg, I can see your point now. Indeed the whole chapter on type deduction in Effective Modern C++ (by Scott Meyers) shows the difficulties of type deduction.

One concern I have, and one of the reasons I use `auto` as much as I can is to avoid implicit type conversions. For instance
```c++
bool MemoryFreeSpaceManager::tryAllocate(uint64_t size, uint64_t alignment, ll::impl::MemoryAllocationTryInfo& tryInfoOut) noexcept {

    auto offsetMask  = uint64_t{0};
    // auto maskCounter = alignment;
    uint32_t maskCounter = alignment;
```
does not throw any compile time error or warning about the narrowing of `alignment` to `uint32_t`. This can be fixed by using `-Werror -Wshorten-64-to-32` flags during compilation (in fact I will add them).

Things like that generate runtime-errors very hard to catch. I have seen bugs like that in production code, and they are nasty.

I will improve code readability with explicit types where necessary. Thanks for your comments :+1:
